name: data-sync

on:
  workflow_dispatch: # manual button
  schedule:
    - cron: "0 * * * *" # hourly (top of the hour)

concurrency:
  group: data-sync
  cancel-in-progress: true # prevents overlap if a run is slow

jobs:
  sync:
    runs-on: ubuntu-latest

    env:
      # Make all secrets available as environment variables
      SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
      SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
      SPOTIFY_REFRESH_TOKEN: ${{ secrets.SPOTIFY_REFRESH_TOKEN }}
      STRAVA_CLIENT_ID: ${{ secrets.STRAVA_CLIENT_ID }}
      STRAVA_CLIENT_SECRET: ${{ secrets.STRAVA_CLIENT_SECRET }}
      STRAVA_REFRESH_TOKEN: ${{ secrets.STRAVA_REFRESH_TOKEN }}
      WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}

    steps:
      - uses: actions/checkout@v4

      - name: Checkout website repo
        uses: actions/checkout@v4
        with:
          repository: wlmr-rk/wilmerlapuz.com
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          path: website

      - uses: actions/setup-node@v4
        with: { node-version: "18" }

      - run: npm ci --ignore-scripts

      - name: Set website path
        run: echo "WEBSITE_REPO_PATH=${{ github.workspace }}/website" >> $GITHUB_ENV

      # --- run the four fetchers ---
      - run: node scripts/fetch-spotify.js
      - run: node scripts/fetch-strava.js
      - run: node scripts/fetch-leetcode.js
      - run: node scripts/fetch-wakatime.js

      # --- push whatever JSON files were created ---
      - name: Push changes to website
        run: |
          cd website
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add public/*.json || true
          git commit -m "chore: update data from proj-nexus" || exit 0
          git push
